# Generated by Django 5.2.11 on 2026-02-08 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='placeinvite',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='placeinvite',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
