# Generated by Django 5.2.11 on 2026-03-07 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_settlement_cycle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('payment_request', 'Payment Request'), ('balance_updated', 'Balance Updated'), ('welcome', 'Welcome'), ('unsettled_balance', 'Unsettled Balance'), ('expense_added', 'Expense Added'), ('cycle_ended', 'Cycle Ended')], max_length=40),
        ),
    ]
